name = "SLIMregistryJL"
uuid = "f7f9b540-d1a6-11e9-1db1-8fb8d0821f2f"
repo = "https://github.com/slimgroup/SLIMregistryJL.git"

description = """
SLIM's (slim.gatech.edu) Julia package registry.
"""

[packages]
bb331ad6-a1cf-11e9-23da-9bcb53c69f6f = {name = "JOLI", path = "JOLI"}
c228d1c8-a1cf-11e9-3cb4-9bd0a4cd14fc = {name = "JOLI4Flux", path = "JOLI4Flux"}
f3b833dc-6b2e-5b9c-b940-873ed6319979 = {name = "JUDI", path = "JUDI"}
64d089a9-642e-40bf-b992-0fb13636391a = {name = "JUDI4Flux", path = "JUDI4Flux"}
157a0f19-4d44-4de5-a0d0-07e2f0ac4dfa = {name = "SegyIO", path = "SegyIO"}
46767539-6b09-4d43-90af-09e8ecbe3fb9 = {name = "GenSPGL", path = "GenSPGL"}
ec01cecc-7e11-4d3c-aa64-6742d033dd8e = {name = "CloudExtras", path = "CloudExtras"}
23f7647f-51ad-45b5-ae2a-ffae49347e76 = {name = "CloudSegyIO", path = "CloudSegyIO"}
1749d201-7e2c-4f32-afd0-28b1f357fcf8 = {name = "SeisJOLI", path = "SeisJOLI"}
1a9a6158-f1f5-11e9-0746-05ab7d8dcde1 = {name = "RCAM", path = "RCAM"}
85339ca7-91d8-4c2d-a861-347188ab7890 = {name = "AWSpricing", path = "AWSpricing"}
